// <auto-generated />
using System;
using InteractiveGameApi.InteractiveGame.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractiveGameApi.Migrations
{
    [DbContext(typeof(InteractiveGameDbContext))]
    partial class InteractiveGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("InteractiveGameApi.InteractiveGame.DAL.Entities.PotentiometerResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMistakes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PotentiometerResults");
                });
#pragma warning restore 612, 618
        }
    }
}
